framework:
    workflows:
        task:
            type: state_machine
            supports:
                - Entity\Task
            places:
                - backlog
                - in_progress
                - done
            transitions:
                processing:
                    from: backlog
                    to: in_progress
                done:
                    from: in_progress
                    to: done
        article:
            type: workflow
            supports:
                - Entity\Article
            places:
                - draft
                - wait_for_journalist
                - wait_for_spellchecker
            transitions:
                request_review:
                    from: draft
                    to:
                        - wait_for_journalist
                        - wait_for_spellchecker