parameters:


framework:
    # lots of
    # other symfony framework
    # config here
    workflows:
        # type by default always workflow
        # example of access $stateMachine = $this->get('state_machine.simple_state_machine_example');
        simple_state_machine_example: # this definition in used for access in whole project
            supports:
                - App\Entity\SimpleStateMachineExample
            type: 'state_machine'
            places:
                - a
                - b
                - c
            transitions:
                start:
                    from: a
                    to: b
                end:
                    from: b
                    to: c